version: "3.8"

services:
  nginx:
    depends_on:
      - certbot
      - portfolio_web_app
    container_name: portfolio_nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    networks:
      - portfolio_network
    restart: always
    tty: true

  certbot:
    # docker compose run --rm certbot renew
    image: certbot/certbot:latest
    volumes:
      - ./certbot/conf/:/etc/letsencrypt/:rw

  portfolio_web_app:
    depends_on:
      - certbot
    container_name: portfolio_web_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    networks:
      - portfolio_network
    expose:
      - 3000
    tty: true

networks:
  portfolio_network:
    driver: bridge
