import clsx from "clsx";
import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { Inter } from "next/font/google";

import { links } from "@/data";
import { Container, GlobalLayout, Navigation } from "@/shared/ui";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={clsx(inter.className, "bg-white dark:bg-zinc-950")}>
        <ThemeProvider enableSystem disableTransitionOnChange>
          <GlobalLayout>
            <Navigation links={links} />
            <Container>{children}</Container>
          </GlobalLayout>
        </ThemeProvider>
      </body>
    </html>
  );
}
