import type { MDXComponents } from "mdx/types";
import Zoom from "react-medium-image-zoom";

import {
  Accordion,
  Alert,
  AppleNavbarLayout,
  ArrowLink,
  Avatar,
  Badge,
  Breadcrumbs,
  Button,
  Callout,
  Card,
  Checkbox,
  Chip,
  CodeSandbox,
  Container,
  CopyToClipboard,
  Details,
  Dialog,
  Divider,
  DotPattern,
  DynamicImage,
  Emoji,
  Feedback,
  FormField,
  Form,
  Grid,
  IconButton,
  Input,
  KeyBind,
  Link,
  Logo,
  Motion,
  Pagination,
  Paragraph,
  RainbowButton,
  Ratio,
  Regular,
  Safari,
  SearchBar,
  Section,
  SegmentedControl,
  Slider,
  StatusDot,
  Tab,
  Technology,
  Textarea,
  Title,
  Tooltip,
  VideoPlayer,
  Workflows,
} from "@/shared/ui";
import CodeBlock from "@/shared/ui/code-block/code-block";
import Code from "@/shared/ui/code/code";
import AnimatedBeam from "@/shared/ui/animated-beam/animated-beam";
import AnimatedGradientText from "@/shared/ui/animated-gradient-text/animated-gradient-text";
import AnimatedShinyText from "@/shared/ui/animated-shiny-text/animated-shiny-text";
import BorderBeam from "@/shared/ui/border-beam/border-beam";
import CodeComparison from "@/shared/ui/code-comparison/code-comparison";
import FileTree from "@/shared/ui/file-tree/file-tree";
import Iphone15Pro from "@/shared/ui/iphone-15-pro/iphone-15-pro";
import MotionPicture from "@/shared/ui/motion-picture/motion-picture";
import NeonGradientCard from "@/shared/ui/neon-gradient-card/neon-gradient-card";
import ShineBorder from "@/shared/ui/shine-border/shine-border";
import SparklesText from "@/shared/ui/sparkles-text/sparkles-text";
import TweetCard from "@/shared/ui/tweet-card/tweet-card";
import Typography from "@/shared/ui/typography/typography";

export const useMDXComponents = (components: MDXComponents) => ({
  p: Paragraph,
  ...components,
  Accordion,
  Alert,
  AnimatedBeam,
  AnimatedGradientText,
  AnimatedShinyText,
  AppleNavbarLayout,
  ArrowLink,
  Avatar,
  Badge,
  BorderBeam,
  Breadcrumbs,
  Button,
  Callout,
  Card,
  Checkbox,
  Chip,
  Code,
  CodeBlock,
  CodeComparison,
  CodeSandbox,
  Container,
  CopyToClipboard,
  Details,
  Dialog,
  Divider,
  DotPattern,
  DynamicImage,
  Emoji,
  Feedback,
  FileTree,
  FormField,
  Form,
  Grid,
  IconButton,
  Input,
  Iphone15Pro,
  KeyBind,
  Link,
  Logo,
  Motion,
  MotionPicture,
  NeonGradientCard,
  Pagination,
  Paragraph,
  RainbowButton,
  Ratio,
  Regular,
  Safari,
  SearchBar,
  Section,
  SegmentedControl,
  ShineBorder,
  Slider,
  SparklesText,
  StatusDot,
  Tab,
  Technology,
  Textarea,
  Title,
  Tooltip,
  TweetCard,
  Typography,
  VideoPlayer,
  Workflows,
  Zoom,
});
