name: 🎡 Check Dependencies

on: 
  schedule:
    - cron: '0 0 * * 5'

jobs:
  check-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: ⚒ Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: 🧪 Check for outdated dependencies
        run: npx npm-check-updates > check-updates.log

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: dependencies-report
          path: check-updates.log
