name: 🧤 Manually deploying

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write

    steps:
      - uses: actions/checkout@main
      - name: Use Node.js {{ matrix.node-version }}
        uses: actions/setup-node@main
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: ✅ Install dependencies
        run: npm i --legacy-peer-deps

      - name: 🚀 Build and deploy
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: npx vercel --prod --yes --token $VERCEL_TOKEN
