name: 👷‍♂️ Rebuild by article changes

on:
  push:
    branches:
      - main
    paths: ["(resources)/**", "public/**"]

  pull_request:
    branches:
      - main
    paths: ["(resources)/**", "public/**"]

jobs:
  release-by-resources:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install dependencies
        run: npm i
      - name: Release new version
        run: npm run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and deploy
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: npx vercel --prod --token $VERCEL_TOKEN
