name: 🧪 Run unit tests

on:
  push:
    paths: ["**.ts", "**.tsx"]

env:
  NEXT_PUBLIC_LINKEDIN_PROFILE_URL: /your-linkedin-profile
  NEXT_PUBLIC_GITHUB_PROFILE_URL: /your-github-profile
  NEXT_PUBLIC_TWITTER_PROFILE_URL: /your-twitter-profile
  GOOGLE_FORM_URL: /your-google-form-url

jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      pull-requests: read

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - run: npm i --legacy-peer-deps
      - run: npm run test
      - run: npm run type:check
      - run: npm run lint
      - run: npm run build
